# Generated by Django 3.1.5 on 2021-01-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='book',
            new_name='cafea',
        ),
    ]
